# Default values for myzomato-microservices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# image:
#   repository: nginx
#   pullPolicy: IfNotPresent
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: ""

image:
  baseurl: "ayuzzz1995/myzomato"

images:
  orderPaymentProcessingCommand : "orderpaymentprocessing-command"
  orderscommand : "orders-command"
  productquery : "product-query"
  restaurantsquery : "restaurants-query"
  usermanagementquery : "usermanagement-query"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentnames:
  orderPaymentProcessingCommand : "orderpaymentprocessingcommand-deployment"
  orderscommand : "orderscommand-deployment"
  productquery : "productquery-deployment"
  restaurantsquery : "restaurantsquery-deployment"
  usermanagementquery : "usermanagementquery-deployment"

containernames:
  orderPaymentProcessingCommand : "orderpaymentprocessingcommand-container"
  orderscommand : "orderscommand-container"
  productquery : "productquery-container"
  restaurantsquery : "restaurantsquery-container"
  usermanagementquery : "usermanagementquery-container"

servicenames:
  orderPaymentProcessingCommand : 
    name : "orderpaymentprocessingcommand-service"
    loadBalancerPort : 30000
  orderscommand :
    name : "orderscommand-service"
    loadBalancerPort : 30001
  productquery :
    name : "productquery-service"
    loadBalancerPort : 30002
  restaurantsquery :
    name : "restaurantsquery-service"
    loadBalancerPort : 30003
  usermanagementquery :
    name : "usermanagementquery-service"
    loadBalancerPort : 30004

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
